### PR TITLE
Fix for factor-bundle + watchify + gulp 'EventEmitter memory leak detected' issue

### PR DESCRIPTION
**Pull request by ypt**
Implemented the fix for #64 suggested by @Freyert

### CODE REVIEW

**Comment by rtibbles** [comment]
Could this be merged? Pretty handy to have it in master.

**Comment by davidlanger** [comment]
+1

**Comment by Freyert** [comment]
#proud

**Comment by zoubin** [comment]
Right now you can specify `opts.outputs` as a function, and thus no need to plugin `factor-bundle` each time `reset`.

I have tried some way to [use watchify with factor-bundle](https://github.com/zoubin/gulp-watchify-factor-bundle), no memory leak detected. 

I think plugging `factor-bundle` repeatedly seems a little odd, because `reset` only rebuild the pipeline, and all other plugins are plugged only once.

**Comment by davidchase** [comment]
@zoubin you are correct i tired it out by moving `factor-bundle` outside of my re-bundling method and it works therefore this fix is un-needed at least for me as well.

**Comment by rtibbles** [comment]
I think this may be my issue as well.

**Comment by ypt** [comment]
Alright, it sounds like this fix isn't really necessary, and @zoubin and @davidchase have solutions. I'll close this PR.

**Pull request closed without merging**
