### PR TITLE
reconstruct outputs every `addHooks` (to make it compatible with watchify)

### LINKED ISSUE #68: Broken command line outpipe
According to the [command line outpipe example](https://www.npmjs.com/package/factor-bundle#command-line-outpipe-example) section in the README file I should be able to run this command:

``` bash
browserify ./assets/scripts/*.js -p [ factor-bundle -o 'uglify-js -cm > ./public/scripts/`basename $FILE`.js' ] -o ./public/scripts/common.js
```

But I'm getting the following error:

``` bash
var outputs = defined(outopt, []).map(function (o) {
                                      ^
TypeError: undefined is not a function
    at f (/project/node_modules/factor-bundle/index.js:34:39)
    at Browserify.plugin (/project/node_modules/browserify/index.js:350:9)
    at /project/node_modules/browserify/bin/args.js:102:15
    at Array.forEach (native)
    at module.exports (/project/node_modules/browserify/bin/args.js:97:10)
    at Object.<anonymous> (/project/node_modules/browserify/bin/cmd.js:6:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```

### PR DESCRIPTION
**Pull request by jcppman**
fix #68, #63 

- To avoid writing to ended writeStream, outputs will be constructed everytime
- In the scenario that user wanna use outpipe, the `outopt` will be
kept as string, so we can determine the user's attempt in later codes
and do the relavant opperations

### CODE REVIEW

**Comment by dgbeck** [comment]
Thanks @jcppman for this patch. However this guy does not work for the case where outputs is an array of streams. I think we may need something like this to fix the issue

https://github.com/Aben/factor-bundle/commit/18692d69d983470857d6d3c6af7b7bd12266714f

**Comment by jcppman** [comment]
added two tests which will fail before applying the patch and will success after applying the patch

**Comment by dgbeck** [comment]
Just opened #75 that incorporates these changes and tests, and also added ability for outputs to be specified as a function for the stream case. Thanks @jcppman.

**Comment by jcppman** [comment]
In my opinion https://github.com/Aben/factor-bundle/commit/18692d69d983470857d6d3c6af7b7bd12266714f is more of a workaround to skip the part that cause the issue (write to end stream).

BTW how about two-ways merging instead of copy-and-paste? I mean, I'm not quite care if i got my name on the commit or not but i guess that's the way open-sourced things work right?

**Comment by dgbeck** [comment]
Sorry u are right. did not mean to side step credit. will do the merge in the future. Thx for vocalizing.

Just want to make sure the stream case is covered as we need it. If there is a better way then let's do it that way

**Comment by jcppman** [comment]
@dgbeck No worry, I'm glad that it's useful to other ppl not just me!

**Comment by substack** [comment]
all sorted in the 2.5.0 release

**Comment by jcppman** [comment]
Fantastic!

**Pull request closed without merging**
