### PR TITLE
Ensure output directory exists before creating write stream

### LINKED ISSUE #83: Errors if directory doesn't exist—browserify does not
Not sure if this is a bug, but if I use browserify to try to write a file to a directory that doesn't yet exist, browserify will create the directory. factor-bundle, however, will throw an error. Is there any reason for the difference in behaviour between the two?

### PR DESCRIPTION
**Pull request by woollybogger**
Fixes #83

### CODE REVIEW

**Comment by woollybogger** [comment]
@substack @terinjokes

**Comment by terinjokes** [comment]
I can understand this functionality being part of the CLI tool, but it doesn't belong as part of the library.

See also https://github.com/substack/factor-bundle/issues/70#issuecomment-148349467

**Comment by woollybogger** [comment]
That sounds reasonable. Would you accept a PR if I added output directory creation to the CLI tool?

**Comment by woollybogger** [comment]
Actually, adding it to the CLI isn't helpful. I'm using factor-bundle with grunt-browserify ([like so](https://github.com/jmreidy/grunt-browserify/blob/master/examples/factor-bundle/Gruntfile.js)) which directly uses `factor-bundle/index.js`, so that's where this needs to live.

**Comment by terinjokes** [comment]
@woollybogger then I think you're best course of action is to create the output directory before using grunt-browserify.

**Comment by woollybogger** [comment]
@terinjokes Yeah that's what I'm currently doing. It's just pretty annoying because it adds 7 extra lines to my Gruntfile :disappointed: (which is also sort of funny because it only takes adding 2 lines in this repo to fix this for everyone). Oh well.

**Pull request closed without merging**
